"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Minus, Plus, ShoppingBag, Trash2, X } from "lucide-react";
import { useState } from "react";
import { calculatePricing, formatMoney } from "@/lib/pricing";
import { OrderSummary } from "@/components/order-summary";
import { useCart } from "@/store/cart";

export default function CartPage() {
  const { items, promoCode, hydrated, setQuantity, removeItem, clearCart, applyPromo, removePromo } = useCart();
  const [code,setCode]=useState(""); const [message,setMessage]=useState(""); const pricing=calculatePricing(items,promoCode);
  if (!hydrated) return <div className="shell py-24 text-center">Loading your bag…</div>;
  if (!items.length) return <div className="shell py-24 text-center"><ShoppingBag className="mx-auto" size={45}/><h1 className="display mt-6 text-6xl">Your bag is light.</h1><p className="mt-4 text-[var(--muted)]">Good things are waiting in the collection.</p><Link className="btn btn-primary mt-8" href="/products">Explore products <ArrowRight size={17}/></Link></div>;
  const submitPromo=(event:React.FormEvent)=>{event.preventDefault();if(applyPromo(code)){setMessage("20% off applied to your merchandise.");setCode("");}else setMessage("That promo code isn’t valid. Try KANE or KANE2026.");};
  return <div className="shell py-14"><div className="flex items-end justify-between"><div><p className="eyebrow">Your selection</p><h1 className="display mt-3 text-6xl">Shopping bag</h1></div><button onClick={clearCart} className="text-sm font-bold underline">Clear bag</button></div>
    <div className="mt-10 grid gap-10 lg:grid-cols-[1.5fr_.7fr]"><section aria-label="Cart items" className="grid content-start gap-4">{items.map((item)=><article key={item.slug} className="card grid grid-cols-[110px_1fr] gap-5 p-4 sm:grid-cols-[140px_1fr]"><Link href={`/products/${item.slug}`} className="relative aspect-[4/5] overflow-hidden rounded-2xl bg-[#eee]"><Image src={item.image} alt={item.name} fill className="object-cover"/></Link><div className="flex flex-col justify-between py-2"><div className="flex justify-between gap-4"><div><p className="eyebrow">{item.category}</p><Link href={`/products/${item.slug}`} className="mt-1 block text-lg font-bold">{item.name}</Link><p className="mt-1 text-sm text-[var(--muted)]">{formatMoney(item.priceCents)} each</p></div><button onClick={()=>removeItem(item.slug)} aria-label={`Remove ${item.name}`} className="h-fit text-[var(--muted)]"><Trash2 size={18}/></button></div><div className="mt-5 flex items-end justify-between"><div className="flex h-10 items-center rounded-full border border-[var(--line)]"><button onClick={()=>setQuantity(item.slug,item.quantity-1)} disabled={item.quantity===1} aria-label={`Decrease ${item.name} quantity`} className="grid h-full w-10 place-items-center disabled:opacity-30"><Minus size={15}/></button><output className="w-8 text-center text-sm font-bold">{item.quantity}</output><button onClick={()=>setQuantity(item.slug,item.quantity+1)} disabled={item.quantity===item.stock} aria-label={`Increase ${item.name} quantity`} className="grid h-full w-10 place-items-center disabled:opacity-30"><Plus size={15}/></button></div><div className="text-right"><p className="text-xs text-[var(--muted)]">Line total</p><strong>{formatMoney(item.priceCents*item.quantity)}</strong></div></div></div></article>)}</section>
      <aside className="card h-fit p-6 lg:sticky lg:top-28"><h2 className="text-xl font-bold">Order summary</h2><form onSubmit={submitPromo} className="mt-6"><label className="text-sm font-bold" htmlFor="promo">Promo code</label>{promoCode ? <div className="mt-2 flex items-center justify-between rounded-xl bg-[#e7f1d5] px-4 py-3 text-sm"><span><strong>{promoCode}</strong> · 20% off</span><button type="button" onClick={removePromo} aria-label="Remove promo"><X size={17}/></button></div> : <div className="mt-2 flex gap-2"><input id="promo" className="field" value={code} onChange={(e)=>setCode(e.target.value)} placeholder="KANE"/><button className="btn btn-secondary !rounded-xl !px-4">Apply</button></div>}{message && <p className={`mt-2 text-xs ${message.startsWith("That")?"text-red-700":"text-[var(--forest)]"}`} role="status">{message}</p>}</form><div className="my-6 border-t border-[var(--line)]"/><OrderSummary pricing={pricing}/><Link href="/checkout" className="btn btn-primary mt-7 w-full">Proceed to checkout <ArrowRight size={17}/></Link><Link href="/products" className="mt-4 block text-center text-sm font-bold underline">Continue shopping</Link></aside>
    </div></div>;
}
