"use client";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Mail, UserRound } from "lucide-react";
import { useState } from "react";
import { AccountShell } from "@/components/account-shell";
import type { SessionUser } from "@/types";

export default function ProfilePage() {
  const client = useQueryClient();
  const { data } = useQuery<{ user: SessionUser }>({ queryKey: ["me"], queryFn: () => fetch("/api/auth/me").then((response) => response.json()) });
  const [status, setStatus] = useState(""); const [saving, setSaving] = useState(false);
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setStatus(""); const name=String(new FormData(event.currentTarget).get("name")??""); const response=await fetch("/api/auth/me",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})}); const result=await response.json(); if(response.ok){client.setQueryData(["me"],result);setStatus("Profile updated.");}else setStatus(result.error??"Could not update profile."); setSaving(false); }
  return <AccountShell title="Profile">{data?.user ? <div className="grid max-w-5xl gap-5 lg:grid-cols-[.75fr_1.25fr]"><section data-reveal className="rounded-[1.6rem] border border-white/10 bg-white/[.025] p-6 sm:p-8"><span className="grid size-20 place-items-center rounded-2xl border border-[var(--accent)]/20 bg-[var(--accent)]/10 text-3xl font-light text-[var(--accent)]">{data.user.name.slice(0,1).toUpperCase()}</span><h2 className="mt-6 text-2xl font-light tracking-[-.035em]">{data.user.name}</h2><p className="mt-2 flex items-center gap-2 text-xs text-[var(--muted)]"><Mail size={13}/>{data.user.email}</p><span className="mt-6 inline-flex rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 font-mono text-[9px] uppercase tracking-[.15em] text-emerald-300">Verified member</span></section><form onSubmit={save} data-reveal className="rounded-[1.6rem] border border-white/10 bg-white/[.025] p-6 sm:p-8"><p className="eyebrow">Personal information</p><h2 className="mt-2 text-3xl font-light tracking-[-.04em]">Make it yours.</h2><label className="mt-8 grid gap-2 text-xs text-[var(--muted)]"><span>Full name</span><span className="relative"><UserRound className="absolute left-4 top-3.5 text-[var(--faint)]" size={17}/><input key={data.user.name} name="name" className="field !pl-11" defaultValue={data.user.name} required minLength={2}/></span></label><label className="mt-5 grid gap-2 text-xs text-[var(--muted)]"><span>Email address</span><input className="field opacity-60" value={data.user.email} readOnly/><small className="text-[10px] text-[var(--faint)]">Your login email cannot be changed in this demo.</small></label>{status&&<p role="status" className="mt-5 flex items-center gap-2 text-xs text-[var(--accent)]"><Check size={14}/>{status}</p>}<button disabled={saving} className="btn btn-primary mt-7">{saving?"Saving…":"Save profile"}</button></form></div> : <p className="text-sm text-[var(--muted)]">Loading profile…</p>}</AccountShell>;
}
