"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, Coins, LogOut, Package } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { formatMoney } from "@/lib/pricing";
import type { SessionUser } from "@/types";

export default function AccountPage(){const router=useRouter();const queryClient=useQueryClient();const {data,isLoading}=useQuery<{user:SessionUser}>({queryKey:["me"],queryFn:async()=>{const r=await fetch("/api/auth/me");if(!r.ok)throw new Error("unauthorized");return r.json();},retry:false});if(isLoading)return <div className="shell py-24">Loading your account…</div>;if(!data?.user)return <div className="shell py-24 text-center"><h1 className="display text-5xl">Your account awaits.</h1><p className="mt-4 text-[var(--muted)]">Sign in or create an account to see your balance and orders.</p><div className="mt-7 flex justify-center gap-3"><Link href="/signin" className="btn btn-primary">Sign in</Link><Link href="/signup" className="btn btn-secondary">Create account</Link></div></div>;const user=data.user;async function signout(){await fetch("/api/auth/signout",{method:"POST"});queryClient.clear();router.push("/");router.refresh();}return <div className="shell py-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Your account</p><h1 className="display mt-3 text-6xl">Hello, {user.name.split(" ")[0]}.</h1><p className="mt-3 text-[var(--muted)]">{user.email}</p></div><button onClick={signout} className="btn btn-secondary"><LogOut size={17}/> Sign out</button></div><div className="mt-10 grid gap-5 md:grid-cols-2"><section className="overflow-hidden rounded-[30px] bg-[var(--forest)] p-8 text-white"><Coins/><p className="mt-12 text-xs font-bold tracking-[.16em] text-white/60 uppercase">Available Telapsy Balance</p><p className="display mt-2 text-6xl">{formatMoney(user.balanceCents)}</p><p className="mt-4 text-sm text-white/60">Fictional demo funds · No real-world monetary value</p></section><Link href="/orders" className="card group p-8"><Package/><p className="eyebrow mt-12">Order history</p><div className="mt-2 flex items-end justify-between"><h2 className="display text-4xl">My Orders</h2><ArrowRight className="transition group-hover:translate-x-1"/></div><p className="mt-4 text-sm text-[var(--muted)]">Review every product, price, discount, and delivery detail.</p></Link></div></div>}
